# Generated by Django 3.1.3 on 2021-01-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
