<<<<<<< HEAD
# Generated by Django 3.1.3 on 2021-01-16 19:29
=======
# Generated by Django 3.1.5 on 2021-01-15 03:55
>>>>>>> a9da69bc600b831165ada616637a5efd2d816871

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('viewed', models.BooleanField(default=False)),
            ],
        ),
    ]
