# Generated by Django 3.1.3 on 2021-01-04 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notification', '0001_initial'),
        ('recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_id', to='recipe_app.recipe'),
        ),
    ]
