<<<<<<< HEAD:recipe_app/migrations/0002_auto_20210116_1929.py
# Generated by Django 3.1.3 on 2021-01-16 19:29
=======
# Generated by Django 3.1.5 on 2021-01-15 03:55
>>>>>>> a9da69bc600b831165ada616637a5efd2d816871:recipe_app/migrations/0002_auto_20210115_0355.py

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='saved',
            field=models.ManyToManyField(related_name='saved', to=settings.AUTH_USER_MODEL),
        ),
    ]
