<<<<<<< HEAD:recipe_app/migrations/0002_auto_20210116_1939.py
# Generated by Django 3.1.3 on 2021-01-16 19:39
=======
# Generated by Django 3.1.5 on 2021-01-16 19:15
>>>>>>> c78f66825fb06b82297a99b33622225f205915ed:recipe_app/migrations/0002_auto_20210116_1915.py

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='saved',
            field=models.ManyToManyField(related_name='saved', to=settings.AUTH_USER_MODEL),
        ),
    ]
