# Generated by Django 3.1.5 on 2021-01-07 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0003_auto_20210107_0338'),
        ('recipe_app', '0003_auto_20210106_1911'),
    ]

    operations = [
    ]
